// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgVrsHW7MzvwKBiIXXqt2zHeI9NpJ7pp8',
    appId: '1:896950306295:web:59e2a677fc9efab6b69af2',
    messagingSenderId: '896950306295',
    projectId: 'nauta-tours',
    authDomain: 'nauta-tours.firebaseapp.com',
    storageBucket: 'nauta-tours.firebasestorage.app',
    measurementId: 'G-743FVWPD4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR3-4mD1xgpYCgBM9R-AyrLvxZqmQbYQE',
    appId: '1:896950306295:android:60691b44b59a9c9cb69af2',
    messagingSenderId: '896950306295',
    projectId: 'nauta-tours',
    storageBucket: 'nauta-tours.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBihucS1U7hPJGHHRFAPgbnCEGN5GqadjY',
    appId: '1:896950306295:ios:0c7b9b5deba881e8b69af2',
    messagingSenderId: '896950306295',
    projectId: 'nauta-tours',
    storageBucket: 'nauta-tours.firebasestorage.app',
    iosBundleId: 'com.example.nautaTours',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBihucS1U7hPJGHHRFAPgbnCEGN5GqadjY',
    appId: '1:896950306295:ios:0c7b9b5deba881e8b69af2',
    messagingSenderId: '896950306295',
    projectId: 'nauta-tours',
    storageBucket: 'nauta-tours.firebasestorage.app',
    iosBundleId: 'com.example.nautaTours',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgVrsHW7MzvwKBiIXXqt2zHeI9NpJ7pp8',
    appId: '1:896950306295:web:a2498abc8d1d831eb69af2',
    messagingSenderId: '896950306295',
    projectId: 'nauta-tours',
    authDomain: 'nauta-tours.firebaseapp.com',
    storageBucket: 'nauta-tours.firebasestorage.app',
    measurementId: 'G-G1D5RKBHJL',
  );
}
